services:
  - type: web
    name: agenticseek
    env: python
    buildCommand: |
      apt-get update && apt-get install -y portaudio19-dev &&
      pip install -r requirements.txt
    startCommand: uvicorn app:app --host=0.0.0.0 --port=10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
